%global app_name smemaster
# x-release-please-start-version
%global app_version 0.4.22
# x-release-please-end
%global app_release 1

Name:    %{app_name}
Version: %{app_version}
Release: %{app_release}%{?dist}
Summary: SME email, automation, and lightweight CRM workspace

License: Apache-2.0
URL:     https://github.com/Zakarialabib/smeMaster
Source0: %{url}/archive/v%{version}/%{name}-%{version}.tar.gz

# Build Dependencies
BuildRequires: rust
BuildRequires: cargo
BuildRequires: nodejs
BuildRequires: webkit2gtk4.1-devel
BuildRequires: openssl-devel
BuildRequires: libappindicator-gtk3-devel
BuildRequires: librsvg2-devel
BuildRequires: desktop-file-utils

# Runtime Dependencies
Requires: webkit2gtk4.1
Requires: openssl
Requires: libappindicator-gtk3
Requires: hicolor-icon-theme

%description
SMEMaster is an open-source local-first desktop workspace for SME email
operations, automation marketing, and lightweight CRM workflows built with
Tauri, React, and Vite.

%prep
%setup -q -n %{name}-%{version}

%build
# Install Node.js dependencies
npm ci

# Build the Tauri application binary and generate RPM
npx tauri build -b rpm

%install
# Extract the RPM generated by Tauri into the buildroot
cd %{buildroot}
rpm2cpio %{_builddir}/%{name}-%{version}/src-tauri/target/release/bundle/rpm/*.rpm | cpio -idmv

%files
%{_bindir}/%{app_name}
%{_datadir}/applications/SMEMaster.desktop
%{_datadir}/icons/hicolor/32x32/apps/%{app_name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{app_name}.png
%{_datadir}/icons/hicolor/256x256/apps/%{app_name}.png
%license LICENSE

%changelog
* Fri Feb 20 2026 Camden Bock <camden.bock@maine.edu> - 0.4.10-1
- Initial RPM packaging


