export interface CampaignPreset {
  id: string;
  name: string;
  subject: string;
  bodyHtml: string;
  category: 'marketing' | 'sales' | 'customer_success' | 'transactional';
}

export const campaignPresets: CampaignPreset[] = [
  {
    id: 'campaign-product-launch',
    name: 'Product Launch',
    subject: 'Introducing our latest product',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:28px 32px;text-align:center;"><h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;">New Product Launch</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:26px;color:#18181b;font-weight:700;line-height:1.3;">Meet Our Latest Innovation</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#6366f1;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Learn More →</a></td></tr><tr><td style="padding:24px 32px;background:#fafafa;border-top:1px solid #e4e4e7;text-align:center;font-size:12px;color:#a1a1aa;"><p style="margin:0 0 4px;">{{company}} — All rights reserved.</p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-feature-release',
    name: 'Feature Release',
    subject: 'New feature alert: {{subject}}',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#2563eb;padding:20px 32px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="font-size:14px;color:#93c5fd;">Feature Update</td><td align="right" style="font-size:20px;color:#ffffff;font-weight:700;">{{company}}</td></tr></table></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Introducing {{subject}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#2563eb;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">See What Is New →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}} — All rights reserved.</p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-webinar-invite',
    name: 'Webinar Invite',
    subject: 'You are invited to our webinar',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#059669,#10b981);padding:36px 32px;text-align:center;"><p style="margin:0 0 8px;font-size:14px;color:#a7f3d0;text-transform:uppercase;letter-spacing:2px;">Webinar</p><h1 style="margin:0;font-size:28px;color:#ffffff;font-weight:800;line-height:1.3;">You Are Invited</h1></td></tr><tr><td style="padding:32px 32px 0;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:12px;background:#f0fdf4;border-radius:8px;font-size:14px;color:#065f46;"><strong>Topic:</strong> {{subject}}<br><strong>Duration:</strong> 45 minutes + Q&A</td></tr></table></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#059669;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Register Now →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-case-study',
    name: 'Case Study',
    subject: 'How {{customer_name}} succeeded with {{company}}',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#27272a;padding:24px 32px;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">Case Study</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">{{customer_name}} x {{company}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;border-radius:8px;"><tr><td style="padding:16px;font-size:13px;color:#52525b;"><strong>Key Results:</strong><br>• 40% increase in efficiency<br>• 60% reduction in manual work<br>• 3x ROI within first quarter</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#27272a;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Read Full Story →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-newsletter-monthly',
    name: 'Monthly Newsletter',
    subject: 'Your monthly update from {{company}}',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#18181b;padding:20px 32px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="font-size:14px;color:#a1a1aa;">Monthly Newsletter</td><td align="right" style="font-size:20px;color:#ffffff;font-weight:700;">{{company}}</td></tr></table></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">This Month in Review</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 24px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:8px 0;border-top:1px solid #e4e4e7;"><a href="#" style="font-size:14px;color:#6366f1;text-decoration:none;">› Featured article: {{subject}}</a></td></tr><tr><td style="padding:8px 0;border-top:1px solid #e4e4e7;"><a href="#" style="font-size:14px;color:#6366f1;text-decoration:none;">› Product updates and improvements</a></td></tr><tr><td style="padding:8px 0;border-top:1px solid #e4e4e7;"><a href="#" style="font-size:14px;color:#6366f1;text-decoration:none;">› Community highlights</a></td></tr></table></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}} — All rights reserved.</p><p style="margin:0;"><a href="#" style="color:#6366f1;text-decoration:underline;">Unsubscribe</a></p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-newsletter-weekly',
    name: 'Weekly Digest',
    subject: 'Your weekly digest from {{company}}',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#7c3aed;padding:16px 32px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="font-size:12px;color:#c4b5fd;">Weekly Digest</td><td align="right" style="font-size:16px;color:#ffffff;font-weight:700;">{{company}}</td></tr></table></td></tr><tr><td style="padding:24px 32px 0;"><h1 style="margin:0;font-size:22px;color:#18181b;font-weight:700;line-height:1.3;">This Week at {{company}}</h1></td></tr><tr><td style="padding:12px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 24px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:8px 12px;background:#f5f3ff;border-radius:6px;font-size:13px;color:#5b21b6;">📌 Top story: {{subject}}</td></tr></table></td></tr><tr><td style="padding:16px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p><p style="margin:0;"><a href="#" style="color:#7c3aed;text-decoration:underline;">Manage preferences</a></p></td></tr></table></td></tr></table>`,
    category: 'marketing',
  },
  {
    id: 'campaign-drip-5-email',
    name: '5-Email Drip Campaign',
    subject: 'Series: {{subject}} — Part 1',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#dc2626,#f97316);padding:20px 32px;text-align:center;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:700;">Drip Series</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Welcome to the Series</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="font-size:12px;color:#a1a1aa;text-align:center;">Part 1 of 5 — {{subject}}</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#f97316;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Read On →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'sales',
  },
  {
    id: 'campaign-re-engagement',
    name: 'Re-Engagement',
    subject: 'We miss you at {{company}}',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#e11d48;padding:24px 32px;text-align:center;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">We Miss You</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Come Back to {{company}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;text-align:center;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#e11d48;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Redeem Your Offer →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p><p style="margin:0;"><a href="#" style="color:#e11d48;text-decoration:underline;">Unsubscribe</a></p></td></tr></table></td></tr></table>`,
    category: 'sales',
  },
  {
    id: 'campaign-upsell',
    name: 'Upsell Offer',
    subject: 'Upgrade your {{company}} plan',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#1c1917;padding:24px 32px;text-align:center;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:700;">Exclusive Upgrade</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:26px;color:#18181b;font-weight:800;line-height:1.3;">Go Pro with {{company}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:10px 16px;background:#fef3c7;border-radius:6px;text-align:center;font-size:14px;color:#92400e;"><strong>Limited time:</strong> 20% off annual plans</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#f59e0b;color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;padding:13px 36px;border-radius:8px;">Upgrade Now →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'sales',
  },
  {
    id: 'campaign-cross-sell',
    name: 'Cross-Sell Offer',
    subject: 'You might also like this',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#0284c7;padding:24px 32px;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">Recommended for You</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Complement Your {{company}} Plan</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:10px 12px;background:#f0f9ff;border-left:3px solid #0284c7;font-size:13px;color:#075985;">✓ Seamless integration with your current setup</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#0284c7;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Learn More →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'sales',
  },
  {
    id: 'campaign-trial-expiration',
    name: 'Trial Expiration Notice',
    subject: 'Your {{company}} trial ends soon',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#f59e0b;padding:20px 32px;"><h1 style="margin:0;font-size:16px;color:#ffffff;font-weight:600;">Trial Ending Soon</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Your Free Trial Is Almost Over</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:10px 12px;background:#fefce8;border-radius:6px;font-size:13px;color:#854d0e;text-align:center;">⏰ Your trial expires in {{days_remaining}} days</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#f59e0b;color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;padding:13px 36px;border-radius:8px;">Upgrade Now →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'sales',
  },
  {
    id: 'campaign-onboarding-3-email',
    name: '3-Email Onboarding Sequence',
    subject: 'Welcome to {{company}} — Step 1 of 3',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#6366f1,#a78bfa);padding:28px 32px;text-align:center;"><h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;">Welcome to {{company}}</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Let Us Get You Started</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:8px 12px;background:#f5f3ff;border-radius:6px;font-size:13px;color:#5b21b6;"><strong>Step 1 of 3:</strong> Set up your profile</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#6366f1;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Get Started →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'customer_success',
  },
  {
    id: 'campaign-nps-survey',
    name: 'NPS Survey',
    subject: 'How likely are you to recommend {{company}}?',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#9333ea;padding:24px 32px;text-align:center;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">Quick Survey</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">How Are We Doing?</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;text-align:center;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#9333ea;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Take the Survey →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'customer_success',
  },
  {
    id: 'campaign-referral-request',
    name: 'Referral Request',
    subject: 'Know someone who needs {{company}}?',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#059669;padding:24px 32px;text-align:center;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">Spread the Word</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Refer a Friend to {{company}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;text-align:center;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="padding:10px 12px;background:#f0fdf4;border-radius:6px;text-align:center;font-size:14px;color:#065f46;"><strong>Reward:</strong> One month free for each referral</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#059669;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Refer Now →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'customer_success',
  },
  {
    id: 'campaign-anniversary',
    name: 'Anniversary',
    subject: 'Celebrating {{years}} years with you',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#991b1b,#dc2626);padding:36px 32px;text-align:center;"><p style="margin:0 0 4px;font-size:28px;line-height:1;">🎉</p><h1 style="margin:8px 0 0;font-size:24px;color:#ffffff;font-weight:800;line-height:1.3;">Happy Anniversary!</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:22px;color:#18181b;font-weight:700;line-height:1.3;">{{years}} Years with {{company}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;text-align:center;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#dc2626;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Claim Your Gift →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'customer_success',
  },
  {
    id: 'campaign-feedback-request',
    name: 'Feedback Request',
    subject: 'Tell us about your experience',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#e11d48;padding:24px 32px;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">We Want to Hear from You</h1></td></tr><tr><td style="padding:32px 32px 0;text-align:center;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">How Was Your Experience?</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;text-align:center;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#e11d48;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Share Feedback →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'customer_success',
  },
  {
    id: 'campaign-order-confirmation',
    name: 'Order Confirmation',
    subject: 'Your order has been confirmed',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#059669;padding:24px 32px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td style="font-size:14px;color:#a7f3d0;">Order Confirmation</td><td align="right" style="font-size:12px;color:#a7f3d0;">#{{order_number}}</td></tr></table></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Thank You for Your Order</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f0fdf4;border-radius:6px;"><tr><td style="padding:12px 16px;font-size:13px;color:#065f46;">✓ Payment received<br>✓ Order being processed<br>✓ You will receive a shipping confirmation soon</td></tr></table></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'transactional',
  },
  {
    id: 'campaign-shipping-notification',
    name: 'Shipping Notification',
    subject: 'Your order has shipped',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#2563eb;padding:20px 32px;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">On Its Way!</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:24px;color:#18181b;font-weight:700;line-height:1.3;">Your Package Has Shipped</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td style="padding:0 32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#eff6ff;border-radius:6px;"><tr><td style="padding:12px 16px;font-size:13px;color:#1e40af;"><strong>Tracking:</strong> {{tracking_number}}<br><strong>Carrier:</strong> {{carrier_name}}<br><strong>Estimated delivery:</strong> {{delivery_date}}</td></tr></table></td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#2563eb;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Track Package →</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'transactional',
  },
  {
    id: 'campaign-password-reset',
    name: 'Password Reset',
    subject: 'Reset your {{company}} password',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:#27272a;padding:20px 32px;"><h1 style="margin:0;font-size:16px;color:#ffffff;font-weight:600;">Security Alert</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:22px;color:#18181b;font-weight:700;line-height:1.3;">Password Reset Requested</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#27272a;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Reset Password →</a></td></tr><tr><td style="padding:0 32px 24px;font-size:12px;color:#a1a1aa;text-align:center;">This link expires in 1 hour. If you did not request this, ignore this email.</td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'transactional',
  },
  {
    id: 'campaign-account-verification',
    name: 'Account Verification',
    subject: 'Verify your {{company}} account',
    bodyHtml: `<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;font-family:Arial,Helvetica,sans-serif;"><tr><td align="center" style="padding:32px 16px;"><table cellpadding="0" cellspacing="0" border="0" width="560" style="max-width:100%;background:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:24px 32px;"><h1 style="margin:0;font-size:18px;color:#ffffff;font-weight:600;">Verify Your Email</h1></td></tr><tr><td style="padding:32px 32px 0;"><h1 style="margin:0;font-size:22px;color:#18181b;font-weight:700;line-height:1.3;">Almost There, {{first_name}}</h1></td></tr><tr><td style="padding:16px 32px;font-size:15px;color:#3f3f46;line-height:1.7;">{{content}}</td></tr><tr><td align="center" style="padding:0 32px 32px;"><a href="#" style="display:inline-block;background:#6366f1;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;padding:13px 36px;border-radius:8px;">Verify Account →</a></td></tr><tr><td style="padding:0 32px 24px;font-size:12px;color:#a1a1aa;text-align:center;">This link expires in 24 hours.</td></tr><tr><td style="padding:20px 32px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;text-align:center;"><p style="margin:0 0 4px;">{{company}}</p></td></tr></table></td></tr></table>`,
    category: 'transactional',
  },
];
