export interface WorkflowPreset {
  id: string;
  name: string;
  description: string;
  trigger_event: string;
  trigger_conditions: string;
  actions: string;
  category: 'automation' | 'ai_enhanced';
}

export const WORKFLOW_PRESETS: WorkflowPreset[] = [
  {
    id: "auto-archive-newsletters",
    name: "Auto-archive newsletters",
    description: "Automatically archive emails with 'newsletter' in the subject",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ subject_contains: "newsletter" }),
    actions: JSON.stringify([{ type: "archive" }]),
    category: "automation",
  },
  {
    id: "star-vip-emails",
    name: "Star VIP emails",
    description: "Star emails from your most important clients",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ from_domain: "client.com" }),
    actions: JSON.stringify([{ type: "star" }]),
    category: "automation",
  },
  {
    id: "flag-invoices",
    name: "Flag invoices",
    description: "Apply INVOICE label and star emails with 'invoice' in the subject",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ subject_contains: "invoice" }),
    actions: JSON.stringify([{ type: "apply_label", labelId: "INVOICE" }, { type: "star" }]),
    category: "automation",
  },
  {
    id: "auto-reply-vacation",
    name: "Auto-reply on vacation",
    description: "Send a vacation auto-reply template to all incoming emails",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({}),
    actions: JSON.stringify([{ type: "send_template", templateId: "vacation-reply" }]),
    category: "automation",
  },
  {
    id: "followup-3-days",
    name: "Follow-up after 3 days",
    description: "Create a follow-up task when no reply is received within 3 days",
    trigger_event: "no_reply_after_days",
    trigger_conditions: JSON.stringify({ days: 3 }),
    actions: JSON.stringify([{ type: "create_task", title: "Follow up on email", dueDays: 1 }]),
    category: "automation",
  },
  {
    id: "forward-support",
    name: "Forward support tickets",
    description: "Forward support-related emails to your support team",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ subject_contains: "support" }),
    actions: JSON.stringify([{ type: "forward_to", email: "support@company.com" }]),
    category: "automation",
  },
  {
    id: "weekly-digest-reminder",
    name: "Weekly digest reminder",
    description: "Create a task every Monday morning to send the weekly digest",
    trigger_event: "time_based",
    trigger_conditions: JSON.stringify({ cron: "0 9 * * 1" }),
    actions: JSON.stringify([{ type: "create_task", title: "Send weekly digest", dueDays: 0 }]),
    category: "automation",
  },
  {
    id: "archive-social",
    name: "Archive social notifications",
    description: "Auto-archive and mark as read social media notification emails",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ from_domain: "linkedin.com" }),
    actions: JSON.stringify([{ type: "archive" }, { type: "mark_read" }]),
    category: "automation",
  },
  {
    id: "flag-overdue-replies",
    name: "Flag overdue replies",
    description: "Star and create a task for threads with no reply in 7 days",
    trigger_event: "no_reply_after_days",
    trigger_conditions: JSON.stringify({ days: 7 }),
    actions: JSON.stringify([
      { type: "create_task", title: "Overdue: No reply in 7 days", dueDays: 0 },
      { type: "star" },
    ]),
    category: "automation",
  },
  {
    id: "mark-read-mailing-lists",
    name: "Mark read from mailing lists",
    description: "Auto-mark as read bulk and mailing list emails",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ subject_contains: "unsubscribe" }),
    actions: JSON.stringify([{ type: "mark_read" }]),
    category: "automation",
  },
  {
    id: "ai-smart-categorization",
    name: "Smart categorization",
    description: "Use AI to automatically categorize inbox emails into folders",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "categorize" }),
    actions: JSON.stringify([{ type: "ai_categorize" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-sentiment-routing",
    name: "Sentiment-based routing",
    description: "Route emails to different folders based on AI sentiment analysis",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "sentiment" }),
    actions: JSON.stringify([{ type: "ai_route", target: "sentiment_folder" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-auto-draft",
    name: "AI auto-draft reply",
    description: "Generate a draft reply using AI for common email types",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "auto_draft" }),
    actions: JSON.stringify([{ type: "ai_draft_reply" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-escalation-detector",
    name: "Escalation detector",
    description: "Detect frustrated or urgent language and flag for manager review",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "escalation" }),
    actions: JSON.stringify([{ type: "apply_label", labelId: "NEEDS_REVIEW" }, { type: "notify", role: "manager" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-meeting-handler",
    name: "Meeting request handler",
    description: "Detect meeting requests and auto-suggest time slots",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "meeting_request" }),
    actions: JSON.stringify([{ type: "ai_suggest_slots" }, { type: "create_task", title: "Confirm meeting", dueDays: 0 }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-invoice-processor",
    name: "Invoice data extractor",
    description: "Extract invoice details from email attachments using AI",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "invoice_extract" }),
    actions: JSON.stringify([{ type: "ai_extract_data", schema: "invoice" }, { type: "apply_label", labelId: "INVOICE" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-spam-quarantine",
    name: "AI spam quarantine",
    description: "Use AI to detect sophisticated spam that rule-based filters miss",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "spam_check" }),
    actions: JSON.stringify([{ type: "move_to", folder: "SPAM" }, { type: "notify", role: "user", summary: true }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-language-detect",
    name: "Language detection router",
    description: "Detect email language and route to appropriate team member",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "language_detect" }),
    actions: JSON.stringify([{ type: "ai_route", target: "language_team" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-urgency-scorer",
    name: "Urgency scoring",
    description: "Score incoming emails by urgency and prioritize the inbox",
    trigger_event: "email_received",
    trigger_conditions: JSON.stringify({ ai_prompt: "urgency" }),
    actions: JSON.stringify([{ type: "apply_label", labelId: "URGENT" }, { type: "notify", role: "user" }]),
    category: "ai_enhanced",
  },
  {
    id: "ai-relationship-maintainer",
    name: "Relationship maintainer",
    description: "Suggest check-in emails for contacts you have not spoken to in a while",
    trigger_event: "time_based",
    trigger_conditions: JSON.stringify({ ai_prompt: "relationship", cron: "0 8 * * 1" }),
    actions: JSON.stringify([{ type: "ai_suggest_checkins" }]),
    category: "ai_enhanced",
  },
];
