// ── Crate attributes ─────────────────────────────────────────────────
// No global dead_code allowance – every item is reachable from the binary
// or from other modules. If any false positive appears, add #[allow(dead_code)]
// locally, not here.

mod ai;
mod background;
mod commands;
mod data_cache;
mod db;
pub mod sync_engine;
mod update_tracker;
use commands::IdleRegistry;
use imap::session::SessionPoolManager;
mod contacts;
mod deliverability;
mod device;
mod dns;
mod events;
mod export;
mod imap;
mod jmap;
mod composer;
mod licensing;
mod native_events;
mod notifications;
mod oauth;
mod pairing;
mod pgp;
mod smtp;
mod state;
mod vault;
pub mod orchestrator;
mod invoicing;
mod services;
mod platform;
mod pos;
#[cfg(target_os = "android")]
mod android;
mod assets;
mod auto_launch;
mod drivers;
mod microsoft_graph;
mod error;
mod errors;

use tauri::Manager;
#[cfg(desktop)]
use tauri::Emitter;
use tauri::Listener;
use crate::orchestrator::SystemState;

// NOTE: All #[tauri::command] functions have been moved into the
// `commands::system` submodule. Defining them in lib.rs is no longer
// allowed in Rust 1.86+ because the `__tauri_command_name__` symbol
// generated by the macro cannot be referenced via `crate::*` absolute
// paths from inside the crate root file. See commands/system.rs.

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // ── Panic hook: capture panics to crash.log in app data dir ──────
    std::panic::set_hook(Box::new(|panic_info| {
        let msg = if let Some(s) = panic_info.payload().downcast_ref::<&str>() {
            s.to_string()
        } else if let Some(s) = panic_info.payload().downcast_ref::<String>() {
            s.clone()
        } else {
            "Unknown panic".to_string()
        };
        let location = panic_info.location()
            .map(|l| format!("{}:{}", l.file(), l.line()))
            .unwrap_or_else(|| "unknown location".to_string());
        let backtrace = std::backtrace::Backtrace::capture();
        let log_entry = format!(
            "[panic] {} at {}\n{:?}\n",
            msg, location, backtrace
        );
        // Try to write crash log (best-effort)
        if let Some(data_dir) = dirs::data_dir() {
            let crash_dir = data_dir.join("com.smemaster.app");
            let _ = std::fs::create_dir_all(&crash_dir);
            let _ = std::fs::write(crash_dir.join("crash.log"), &log_entry);
            // Increment crash counter for rollback detection (see update_tracker.rs)
            let crash_count_path = crash_dir.join("crash_count.txt");
            let count: u32 = std::fs::read_to_string(&crash_count_path)
                .ok()
                .and_then(|s| s.trim().parse().ok())
                .unwrap_or(0);
            let _ = std::fs::write(&crash_count_path, (count + 1).to_string());
        }
        eprintln!("{}", log_entry);
    }));

    // Install rustls crypto provider BEFORE any reqwest::Client is created.
    // Required because reqwest uses `rustls-no-provider` feature.
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("Failed to install rustls ring crypto provider");

    // Windows: set explicit AppUserModelID for proper taskbar grouping
    #[cfg(windows)]
    {
        use windows::core::w;
        use windows::Win32::UI::Shell::SetCurrentProcessExplicitAppUserModelID;
        unsafe { let _ = SetCurrentProcessExplicitAppUserModelID(w!("com.smemaster.app")); }
    }

    // ── Base builder ──────────────────────────────────────────────────
    let mut builder = tauri::Builder::default();

    // ── Single‑instance plugin (desktop only) ─────────────────────────
    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_single_instance::init(|app, argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
                let _ = window.unminimize();
            }
            let _ = app.emit("single-instance-args", argv);
        }));
    }

    // ── Deep‑link plugin (always present – mobile & desktop) ─────────
    builder = builder.plugin(tauri_plugin_deep_link::init());

    // ── Biometric plugin (mobile only) ───────────────────────────────
    #[cfg(target_os = "android")]
    {
        builder = builder.plugin(tauri_plugin_biometric::init());
    }

    // ── Updater plugin (optional, behind a feature flag) ─────────────
    #[cfg(feature = "updater")]
    {
        builder = builder.plugin(tauri_plugin_updater::Builder::new().build());
    }

    // ── Android native bridge (mobile only) ──────────────────────────
    #[cfg(target_os = "android")]
    {
        builder = builder.plugin(android::init());
        builder = builder.plugin(android::init_android());
    }

    // ── Core plugins (always active) ──────────────────────────────────
    // Note: tauri-plugin-sql is intentionally removed – all DB access uses sqlx directly.
    builder = builder
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_persisted_scope::init())
        .plugin(tauri_plugin_store::Builder::default().build());

    // ── Window state plugin (desktop only) ────────────────────────────
    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_window_state::Builder::default().build());
    }

    // ── Global shortcut plugin (desktop only) ─────────────────────────
    #[cfg(desktop)]
    {
        builder = builder.plugin(tauri_plugin_global_shortcut::Builder::default().build());
    }

    // ── More core plugins + custom module plugins ─────────────────────
    builder = builder
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(background::init())
        .plugin(notifications::init())
        .plugin(composer::init());

    // native_events bridges Kotlin → Rust events — only relevant on Android
    #[cfg(target_os = "android")]
    {
        builder = builder.plugin(native_events::init());
    }
    
    // NOTE: invoke_handler is registered ONCE via commands::register below.
    // All #[tauri::command] functions (including the lib.rs-level ones) are
    // wired into the master generate_handler! macro in commands/mod.rs.

    // ── Register command handlers from all modules (single source) ───
    builder = commands::register(builder);
    builder = platform::register(builder);
    builder = oauth::register(builder);
    builder = pgp::register(builder);
    builder = vault::register(builder);
    builder = export::register(builder);
    builder = deliverability::register(builder);
    builder = pairing::register(builder);
    builder = device::register(builder);
    builder = assets::register(builder);
    builder = dns::register(builder);
    builder = orchestrator::register(builder);
    builder = licensing::register(builder);

    // ═════════════════════════════════════════════════════════════════
    // 6. Setup closure – runs after all plugins are initialised
    // ═════════════════════════════════════════════════════════════════
    builder = builder.setup(|app| {
        // ── Record app start time as early as possible for accurate uptime
        crate::commands::db::set_app_start_time();

        // ── Reactive data layer: register SQLite change tracker ─────
        let app_handle = app.handle().clone();
        db::change_tracker::register(app_handle);

        // ── Logger – initialised inside setup so we can control level ─
        {
            let level = if cfg!(debug_assertions) {
                log::LevelFilter::Debug
            } else {
                log::LevelFilter::Info
            };
            app.handle().plugin(
                tauri_plugin_log::Builder::default()
                    .level(level)
                    .level_for("sqlx::query", log::LevelFilter::Warn)
                    .build(),
            )?;
        }

        // ── System tray (desktop only) ────────────────────────────────
        #[cfg(desktop)]
        {
            use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
            use tauri::tray::{TrayIconBuilder, TrayIconId};

            let show = MenuItem::with_id(app, "show", "Show SMEMaster", true, None::<&str>)?;
            let check_mail = MenuItem::with_id(app, "check_mail", "Check for Mail", true, None::<&str>)?;
            let mark_all_read = MenuItem::with_id(app, "mark_all_read", "Mark All Read", true, None::<&str>)?;
            let compose_new = MenuItem::with_id(app, "compose_new", "Compose New Message", true, None::<&str>)?;
            let separator1 = PredefinedMenuItem::separator(app)?;
            let relaunch = MenuItem::with_id(app, "relaunch", "Relaunch", true, None::<&str>)?;
            let separator2 = PredefinedMenuItem::separator(app)?;
            let quit = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;

            let menu = Menu::with_items(app, &[
                &show,
                &check_mail,
                &mark_all_read,
                &compose_new,
                &separator1,
                &relaunch,
                &separator2,
                &quit,
            ])?;

            let icon = app.default_window_icon().cloned()
                .expect("default icon must be configured in tauri.conf.json");

            TrayIconBuilder::with_id("main-tray")
                .icon(icon)
                .tooltip("SMEMaster")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "show" => {
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                    "check_mail" => {
                        if let Some(tray) = app.tray_by_id(&TrayIconId::new("main-tray")) {
                            let _ = tray.set_tooltip(Some("Last check: just now"));
                        }
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.emit("tray-check-mail", ());
                        }
                    }
                    "mark_all_read" => {
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.emit("tray:mark-all-read", ());
                        }
                    }
                    "compose_new" => {
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.emit("tray:compose-new", ());
                        }
                    }
                    "relaunch" => {
                        app.restart();
                    }
                    "quit" => {
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.emit("tray:before-quit", ());
                        }
                        std::thread::sleep(std::time::Duration::from_millis(500));
                        app.exit(0);
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let tauri::tray::TrayIconEvent::DoubleClick { .. } = event {
                        let app = tray.app_handle();
                        if let Some(window) = app.get_webview_window("main") {
                            let _ = window.show();
                            let _ = window.set_focus();
                        }
                    }
                })
                .build(app)?;
        }

        // ── Update tray tooltip when sync completes (desktop only) ──
        #[cfg(desktop)]
        {
            let handle = app.handle().clone();
            let handle_for_closure = handle.clone();
            handle.listen("tray:sync-completed", move |_event| {
                let now = chrono::Local::now().format("%H:%M:%S").to_string();
                let _ = crate::commands::system_desktop::set_tray_tooltip(handle_for_closure.clone(), format!("Sync complete: {now}"));
            });
        }

        // ── Desktop: show main window (mobile is handled by Tauri) ───
        #[cfg(desktop)]
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.show();
        }

        // ═════════════════════════════════════════════════════════════
        // Database pool – created synchronously (fast, <50ms).
        // Migration runs in background (non‑blocking) to avoid ANR.
        // ═════════════════════════════════════════════════════════════
        let app_data_dir = app.path().app_data_dir()
            .map_err(|e| format!("Cannot get app data dir: {e}"))?;
        let pool = tauri::async_runtime::block_on(
            db::create_pool(app_data_dir)
        ).map_err(|e| format!("Failed to create DB pool: {e}"))?;

        // ── Note: The FFI change-tracker update_hook is installed on every
        //    new connection inside `db::create_pool` via
        //    `SqlitePoolOptions::after_connect(...)`. No additional wiring
        //    is needed here — the global `db::change_tracker::register(app)`
        //    call above seeds the AppHandle used by the FFI callback.

        // ── Post-migration health check runs inside spawn_orchestrator ──
        app.manage(pool.clone());

        // ── Protocol Driver Registry — maps provider_type to driver impls
        app.manage(drivers::DriverRegistry::new(pool.clone()));

        // ── In-Memory Offline Action Queue (reserved — not wired to runtime)
        // See src-tauri/src/services/offline_queue.rs for details.
        app.manage(crate::services::offline_queue::OfflineQueue::new());

        // ── Licensing state: hardware fingerprint + Ed25519-verifying
        //    license cache. Bound to the SQLite pool so license
        //    activation/validation can persist via `db::license::*`.
        if let Err(e) = licensing::init(app, Some(&pool)) {
            log::warn!("[licensing] Failed to initialise license state: {e}");
        }

        // ── Crypto self‑test: verify encrypt/decrypt round‑trip ──────
        {
            let app_handle = app.handle();
            match oauth::encrypt_token(&app_handle, "__smemaster_crypto_test__") {
                Ok(enc) => {
                    match oauth::decrypt_token(&app_handle, &enc) {
                        Ok(dec) if dec == "__smemaster_crypto_test__" => {
                            log::info!("[crypto] AES-256-GCM encrypt/decrypt OK");
                        }
                        Ok(_) => log::warn!("[crypto] Round‑trip produced different output"),
                        Err(e) => log::warn!("[crypto] Decrypt of self‑encrypted value failed: {e}"),
                    }
                }
                Err(e) => log::warn!("[crypto] Encryption self‑test failed: {e}"),
            }
        }

        // NOTE: rust:init:complete + migration is handled in AppLifecycle::spawn_orchestrator

        // ═════════════════════════════════════════════════════════════
        // EventBus – single source of truth for Rust→React events
        // ═════════════════════════════════════════════════════════════
        let (event_bus, bus_rx) = events::EventBus::new(10_000);
        app.manage(event_bus);

        // SyncMonitorService observes the EventBus
        let sync_monitor = std::sync::Arc::new(orchestrator::SyncMonitorService::new());
        app.manage(sync_monitor.clone());

        let monitor_rx = app.state::<events::EventBus>().subscribe();
        let monitor = sync_monitor.clone();
        tauri::async_runtime::spawn(async move {
            let mut rx = monitor_rx;
            loop {
                match rx.recv().await {
                    Ok(event) => monitor.on_event(&event),
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        log::warn!("[sync-monitor] Lagged, dropped {n} events");
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => {
                        log::info!("[sync-monitor] Channel closed, shutting down");
                        break;
                    }
                }
            }
        });

        // ── Phase 3: Domain Event Processor ──
        crate::events::processor::spawn_domain_event_processor(app.handle());

        // SentinelService (DNS deliverability)
        let sentinel = std::sync::Arc::new(
            deliverability::sentinel::SentinelService::new(app.handle().clone()),
        );
        app.manage(sentinel.clone());

        // ── AI State (on-demand) ──────────────────────────────────────
        // The engine is created immediately, but the LanceDB vector store is
        // opened lazily on the first RAG/index request (see AiState::ensure_vector_db).
        app.manage(crate::commands::ai::AiState::new(app.handle().clone()));

        // Bridge: EventBus → WebView `core-event`
        orchestrator::init::AppLifecycle::spawn_event_bridge(app.handle(), bus_rx);

        // Heartbeat – every 30s, frontend can monitor pipeline health
        orchestrator::init::AppLifecycle::spawn_heartbeat(app.handle());

        // ── Background services moved into spawn_orchestrator ───────────
        // ensure_started() is now called inside AppLifecycle::spawn_orchestrator
        // AFTER migrations complete, so all tables exist when services query them.
        // This prevents the cascade of "no such table" errors seen in v0.8.x.

        // IMAP session pool & IDLE registry (desktop primary, mobile may deactivate)
        app.manage::<SessionPoolManager>(SessionPoolManager::new());
        app.manage::<IdleRegistry>(IdleRegistry::new());

        // Backup scheduler config
        app.manage::<export::scheduler::SharedBackupConfig>(
            std::sync::Arc::new(tokio::sync::RwLock::new(
                export::scheduler::BackupConfig::default(),
            )),
        );

        // ── Phase 3: Subsystem lifecycle state (before spawn so commands can access) ──
        let (subsystem_registry, _tool_registry, state_machine) =
            orchestrator::init::AppLifecycle::wire_subsystem_lifecycle(app);

        // ── AppState: centralized core infrastructure wrapper ──
        // Created here because EventBus is already managed and
        // wire_subsystem_lifecycle has just returned the registry + FSM.
        // The clone is cheap (Arc ref-count bump); subsystem_registry is
        // moved into spawn_orchestrator on the next line.
        {
            let app_state = crate::state::AppState::new(
                app.state::<events::EventBus>().inner().clone(),
                subsystem_registry.clone(),
                state_machine.clone(),
            );
            app.manage(app_state);
        }

        // ── Phase 4: Orchestrator — services lifecycle + Watchdog + migration ──
        orchestrator::init::AppLifecycle::spawn_orchestrator(
            app.handle(),
            pool.clone(),
            subsystem_registry,
        );

        // ── Onboarding completion listener ──
        // The DashMap key change to `String` resolved the previous Send issue,
        // but `block_on` inside a tokio runtime still panics ("runtime within
        // a runtime"), so we keep the dedicated OS thread approach.
        let sm = state_machine.clone();
        app.handle().once("onboarding:completed", move |_| {
            let sm = sm.clone();
            std::thread::spawn(move || {
                tauri::async_runtime::block_on(async move {
                    sm.transition(SystemState::Ready).await;
                    log::info!("[orchestrator] Onboarding completed → Ready (via listener)");
                });
            });
        });

        // NOTE: OAuth token monitor was moved into spawn_orchestrator (Phase 4)
        // to run after migrations complete, preventing "no such table" errors.

        Ok(())
    });

    // ── Window close behaviour – hide instead of close on desktop ────
    builder = builder.on_window_event(|_window, _event| {
        #[cfg(desktop)]
        if let tauri::WindowEvent::CloseRequested { api, .. } = _event {
            if _window.label() == "main" {
                let _ = _window.hide();
                api.prevent_close();
            }
        }
    });

    // ── Run the app (blocking) ────────────────────────────────────────
    builder
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

    log::info!("Tauri application exited normally");

    // ── WAL checkpoint on shutdown: ensure WAL is fully checkpointed ──
    // Note: the pool is dropped at this point (scoped within setup),
    // so this is a safety net — the shutdown should have checkpointed
    // via the orchestrator's graceful_shutdown.
    log::info!("[db] SMEMaster shutdown complete");
}