import { FileBarChart, Scale, TrendingUp, Layers, Wallet, Landmark } from 'lucide-react';
import { formatMoney } from '@features/invoicing/utils/format';
import { useCompanyStore, getActiveCompany } from './companyStore';
import { InfoBanner, SectionCard, DemoBadge } from './erpShared';

const PNL = {
  revenue: 486000,
  cogs: 197000,
  expenses: 142000,
};

const BALANCE = {
  assets: 720000,
  liabilities: 268000,
  equity: 452000,
};

export default function FinancialReports() {
  const companies = useCompanyStore((s) => s.companies);
  const activeCompanyId = useCompanyStore((s) => s.activeCompanyId);
  const company = getActiveCompany(companies, activeCompanyId);

  const grossProfit = PNL.revenue - PNL.cogs;
  const netProfit = grossProfit - PNL.expenses;

  // P&L stacked bar: COGS + Expenses + NetProfit = Revenue
  const pnlSegments = [
    { label: 'COGS', value: PNL.cogs, color: 'bg-danger/70' },
    { label: 'Expenses', value: PNL.expenses, color: 'bg-warning/70' },
    { label: 'Net Profit', value: netProfit, color: 'bg-success/80' },
  ].map((s) => ({ ...s, pct: (s.value / PNL.revenue) * 100 }));

  // Balance sheet stacked bar: Liabilities + Equity = Assets
  const balanceSegments = [
    { label: 'Liabilities', value: BALANCE.liabilities, color: 'bg-accent/70' },
    { label: 'Equity', value: BALANCE.equity, color: 'bg-success/80' },
  ].map((s) => ({ ...s, pct: (s.value / BALANCE.assets) * 100 }));

  return (
    <div className="space-y-5">
      <div className="flex items-center gap-2">
        <h2 className="text-lg font-bold text-text-primary">Financial Reports</h2>
        <DemoBadge />
      </div>

      <InfoBanner>
        Figures are illustrative sample numbers. Real P&amp;L, trial balance, and balance sheet will
        be generated by the Accounting backend (Iteration 5) for{' '}
        <span className="font-medium text-text-primary">{company.name}</span>.
      </InfoBanner>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Profit & Loss */}
        <SectionCard className="p-5">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-9 h-9 rounded-xl bg-accent/10 text-accent flex items-center justify-center shrink-0">
              <TrendingUp size={18} />
            </div>
            <div>
              <h3 className="font-bold text-text-primary">Profit &amp; Loss</h3>
              <p className="text-[11px] text-text-tertiary">Current period (sample)</p>
            </div>
          </div>

          <PnlRow icon={<Wallet size={15} />} label="Revenue" value={PNL.revenue} tone="text-text-primary" />
          <PnlRow icon={<Layers size={15} />} label="Cost of Goods Sold" value={-PNL.cogs} tone="text-danger" />
          <div className="my-2 border-t border-dashed border-border-primary" />
          <PnlRow icon={<TrendingUp size={15} />} label="Gross Profit" value={grossProfit} tone="text-text-primary" bold />
          <PnlRow icon={<FileBarChart size={15} />} label="Operating Expenses" value={-PNL.expenses} tone="text-warning" />
          <div className="my-2 border-t border-border-primary" />
          <PnlRow icon={<TrendingUp size={15} />} label="Net Profit" value={netProfit} tone="text-success" bold large />

          {/* Breakdown bar */}
          <div className="mt-4">
            <div className="flex h-3.5 rounded-full overflow-hidden bg-bg-tertiary">
              {pnlSegments.map((s) => (
                <div key={s.label} className={`${s.color} transition-all`} style={{ width: `${s.pct}%` }} title={`${s.label}: ${formatMoney(s.value)}`} />
              ))}
            </div>
            <div className="flex flex-wrap gap-x-4 gap-y-1.5 mt-2.5">
              {pnlSegments.map((s) => (
                <span key={s.label} className="flex items-center gap-1.5 text-[11px] text-text-tertiary">
                  <span className={`w-2.5 h-2.5 rounded-sm ${s.color}`} /> {s.label}
                </span>
              ))}
            </div>
          </div>
        </SectionCard>

        {/* Balance Sheet */}
        <SectionCard className="p-5">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-9 h-9 rounded-xl bg-success/10 text-success flex items-center justify-center shrink-0">
              <Scale size={18} />
            </div>
            <div>
              <h3 className="font-bold text-text-primary">Balance Sheet</h3>
              <p className="text-[11px] text-text-tertiary">As of period end (sample)</p>
            </div>
          </div>

          <PnlRow icon={<Landmark size={15} />} label="Assets" value={BALANCE.assets} tone="text-text-primary" bold />
          <div className="my-2 border-t border-dashed border-border-primary" />
          <PnlRow icon={<Wallet size={15} />} label="Liabilities" value={BALANCE.liabilities} tone="text-accent" />
          <PnlRow icon={<TrendingUp size={15} />} label="Equity" value={BALANCE.equity} tone="text-success" bold />

          {/* Breakdown bar */}
          <div className="mt-4">
            <div className="flex h-3.5 rounded-full overflow-hidden bg-bg-tertiary">
              {balanceSegments.map((s) => (
                <div key={s.label} className={`${s.color} transition-all`} style={{ width: `${s.pct}%` }} title={`${s.label}: ${formatMoney(s.value)}`} />
              ))}
            </div>
            <div className="flex flex-wrap gap-x-4 gap-y-1.5 mt-2.5">
              {balanceSegments.map((s) => (
                <span key={s.label} className="flex items-center gap-1.5 text-[11px] text-text-tertiary">
                  <span className={`w-2.5 h-2.5 rounded-sm ${s.color}`} /> {s.label}
                </span>
              ))}
            </div>
            <p className="text-[11px] text-text-tertiary mt-2">
              Liabilities + Equity = Assets ({formatMoney(BALANCE.liabilities + BALANCE.equity)})
            </p>
          </div>
        </SectionCard>
      </div>
    </div>
  );
}

function PnlRow({
  icon,
  label,
  value,
  tone,
  bold,
  large,
}: {
  icon: React.ReactNode;
  label: string;
  value: number;
  tone: string;
  bold?: boolean;
  large?: boolean;
}) {
  return (
    <div className="flex items-center justify-between py-1.5">
      <span className={`flex items-center gap-2 ${bold ? 'font-semibold text-text-primary' : 'text-text-secondary'}`}>
        <span className="text-text-tertiary">{icon}</span>
        {label}
      </span>
      <span className={`tabular-nums ${tone} ${bold ? (large ? 'text-lg font-bold' : 'font-bold') : ''}`}>
        {formatMoney(value)}
      </span>
    </div>
  );
}
